#!/bin/sh

cp -r /home/duanshuai/busybox/arm-2014.05/arm-none-linux-gnueabi/libc/lib/* ./rootfs/lib/
cp /home/duanshuai/wifi/ap6212/wpa_supplicant-2.5/wpa_supplicant/wpa_cli ./rootfs/bin
cp /home/duanshuai/wifi/ap6212/wpa_supplicant-2.5/wpa_supplicant/wpa_supplicant ./rootfs/bin
cp /home/duanshuai/wifi/ap6212/wpa_supplicant-2.5/wpa_supplicant/wpa_passphrase ./rootfs/bin
cp /home/duanshuai/wifi/ap6212/libnl-1.1.4/result/lib/libnl.so.1 ./rootfs/lib
cp /home/duanshuai/wifi/ap6212/libnl-1.1.4/result/lib/libnl.so.1.1.4 ./rootfs/lib
mkdir -p ./rootfs/usr/share/udhcpc
cp /home/duanshuai/busybox/busybox-1.28.3/examples/udhcp/simple.script ./rootfs/usr/share/udhcpc/default.script
make_ext4fs -s -l 50331648 -L linux ./system_m3.img ./rootfs
