#!/bin/sh

#设置环境变量
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:
#设置系统运行级别S(single user mode)
runlevel=S
prevlevel=N
#设置新建文件的默认权限022对应644，即rwxrwxrwx === rw-r--r--
umask 022
#传递变量到shell，相当于声明了全局变量
export PATH runlevel prevlevel

echo "********************************************************"
echo "********         start etc/init.d/rc             *******"
echo "********************************************************"

#
# Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
# 捕捉INT QUIT TSTP信号
trap ":" INT QUIT TSTP

#设置机器名
/bin/hostname RK3128

#挂载文件系统,-n表示仅仅挂载而不会去写etc/mtab文件，否则，如果etc在一个只读文件系统
#上，写将会出现错误
#/bin/mount -n -t proc none /proc
#/bin/mount -n -t sysfs none /sys
#/bin/mount -n -t usbfs none /proc/bus/usb
#/bin/mount -t ramfs none /dev

#远程虚拟终端文件设备挂载
#mkdir -p /dev/pts
#/bin/mount -n -t devpts none /dev/pts -o mode=0622

mkdir -p /dev/shm
#/bin/mount -n -t tmpfs tmpfs /dev/shm
#/bin/mount -n -t ramfs none /tmp
#/bin/mount -n -t ramfs none /var

#挂载etc/fstab内的所有内容
mount -a

#内核将自动在/dev目录下创建设备节点
mdev -s

mkdir -p /var/empty
mkdir -p /var/log
mkdir -p /var/log/boa
mkdir -p /var/lock
mkdir -p /var/run
mkdir -p /var/tmp

mkdir -p /opt
mkdir -p /opt/arm

#调用mdev管理程序动态插拔设备，即支持热插拔操作
echo /sbin/mdev > /proc/sys/kernel/hotplug
/bin/hotplug

#记录系统或应用程序产生的各种信息，并写入到日志中 
syslogd

#延时等待wifi驱动安装完毕
sleep 5

/etc/rc.d/init.d/netd start
echo "      " > /dev/ttyS2
echo "***starting networking***" > /dev/ttyS2

/bin/wpa_supplicant -i wlan0 -Dnl80211 -c /etc/wpa_supplicant.conf&
/sbin/udhcpc -i wlan0

#/sbin/ifconfig lo 127.0.0.1
#/etc/init.d/ifconfig-eth0

echo "***********************************************************" 
echo "**************** WaMing GuaGua M3 Pro *********************"
echo "              Kernel version:linux-3.10.49" 
echo "                    Date:2018.5.10" 
echo "**************                          *******************"
echo "***********************************************************"
