#!/bin/dash

TAR="/home/duanshuai/m3/rom/m3"
CPATH="out/target/product/rk312x"
CUR="arch/arm/boot"

cp ${CUR}/zImage ${TAR}/${CPATH} 
cd ${TAR}/${CPATH}
rm kernel
mv zImage kernel
cd ${TAR}
./mkimage.sh ota
