cmd_drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o := arm-eabi-gcc -Wp,-MD,drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/.rkversion.o.d  -nostdinc -isystem /home/duanshuai/m3/rom/m3/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/../lib/gcc/arm-eabi/4.6.x-google/include -I/home/duanshuai/android_source/kernel/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/home/duanshuai/android_source/kernel/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/duanshuai/android_source/kernel/include/uapi -Iinclude/generated/uapi -include /home/duanshuai/android_source/kernel/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -Wno-maybe-uninitialized -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Wall -Wstrict-prototypes -Dlinux -DBCMDRIVER -DSDTEST -DBCMDONGLEHOST -DUNRELEASEDCHIP -DBCMDMA32 -DBCMFILEIMAGE -DDHDTHREAD -DDHD_DEBUG -DSHOW_EVENTS -DBCMDBG -DGET_OTP_MAC_ENABLE -DWIFI_ACT_FRAME -DARP_OFFLOAD_SUPPORT -DSUPPORT_PM2_ONLY -DKEEP_ALIVE -DPKT_FILTER_SUPPORT -DPNO_SUPPORT -DDHDTCPACK_SUPPRESS -DDHD_DONOT_FORWARD_BCMEVENT_AS_NETWORK_PKT -DRXFRAME_THREAD -DBCMSDIOH_TXGLOM_EXT -DWL_EXT_IAPSTA -DENABLE_INSMOD_NO_FW_LOAD -Idrivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd -Idrivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/include -DBCMSDIO -DMMC_SDIO_ABORT -DBCMLXSDMMC -DUSE_SDIOFIFO_IOVAR -DBDC -DPROP_TXSTATUS -DDHD_USE_IDLECOUNT -DBCMSDIOH_TXGLOM -DCUSTOM_SDIO_F2_BLKSIZE=128 -DOOB_INTR_ONLY -DCUSTOMER_OOB -DHW_OOB -DCUSTOMER_HW -DDHD_OF_SUPPORT -DGET_CUSTOM_MAC_ENABLE -DSOFTAP -DWL_WIRELESS_EXT -DUSE_IW -DWL_ESCAN -DWL_CFG80211 -DWLP2P -DWL_CFG80211_STA_EVENT -DWL_ENABLE_P2P_IF -DWL_IFACE_COMB_NUM_CHANNELS -DCUSTOM_ROAM_TRIGGER_SETTING=-65 -DCUSTOM_ROAM_DELTA_SETTING=15 -DCUSTOM_KEEP_ALIVE_SETTING=28000 -DCUSTOM_PNO_EVENT_LOCK_xTIME=7 -DWL_SUPPORT_AUTO_CHANNEL -DWL_SUPPORT_BACKPORTED_KPATCHES -DESCAN_RESULT_PATCH -DVSDB -DWL_CFG80211_VSDB_PRIORITIZE_SCAN_REQUEST -DWLTDLS -DMIRACAST_AMPDU_SIZE=8 -DPROP_TXSTATUS_VSDB -DBUILD_IN_KERNEL    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(rkversion)"  -D"KBUILD_MODNAME=KBUILD_STR(bcmdhd)" -c -o drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.c

source_drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o := drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.c

deps_drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o := \
    $(wildcard include/config/bcmdhd/fw/path.h) \
    $(wildcard include/config/bcmdhd/nvram/path.h) \

drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o: $(deps_drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o)

$(deps_drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o):
